name: panda-demo
region: lon1

services:
  - name: web
    dockerfile_path: Dockerfile
    github:
      repo: tastybamboo/demo
      branch: main
      deploy_on_push: true
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-1gb
    http_port: 80
    health_check:
      http_path: /up
    envs:
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        type: SECRET
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${db.DATABASE_URL}
      - key: SOLID_QUEUE_IN_PUMA
        value: "1"
      - key: APP_HOST
        value: demo.tastybamboo.io
      - key: GITHUB_CLIENT_ID
        type: SECRET
      - key: GITHUB_CLIENT_SECRET
        type: SECRET
      - key: GOOGLE_CLIENT_ID
        type: SECRET
      - key: GOOGLE_CLIENT_SECRET
        type: SECRET
    routes:
      - path: /

  - name: migrate
    dockerfile_path: Dockerfile
    github:
      repo: tastybamboo/demo
      branch: main
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-512mb
    kind: PRE_DEPLOY
    envs:
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        type: SECRET
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${db.DATABASE_URL}
    run_command: >-
      bundle exec rails db:migrate
      && bundle exec rails db:migrate:status

databases:
  - name: db
    engine: PG
    version: "16"
    size: db-s-dev-database
    num_nodes: 1
