test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

digitalocean:
  service: S3
  endpoint: https://<%= ENV.fetch("SPACES_REGION", "lon1") %>.digitaloceanspaces.com
  access_key_id: <%= ENV["SPACES_ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["SPACES_SECRET_ACCESS_KEY"] %>
  region: <%= ENV.fetch("SPACES_REGION", "lon1") %>
  bucket: <%= ENV.fetch("SPACES_BUCKET", "panda-demo") %>
